<!-- Modal -->
<div class="modal fade modal-fullscreen" id="delete-contact-modal" tabindex="-1" role="dialog"
     aria-labelledby="modalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header modal-header-danger">

                <h5 class="modal-title" id="modalLabel">
                    Deseja remover o contato?
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="view-contact-data col-12">

                            <div class="text-center">
                                <img src="/images/loading-spinner.svg" alt="" width="100">
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="deleteContactButton" class="btn btn-danger ">Excluir</button>
            </div>
        </div>
    </div>
</div>