<!-- Modal -->
<div class="modal fade modal-fullscreen" id="account-info-modal" tabindex="-1" role="dialog"
     aria-labelledby="modalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Informações da conta</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="form-contact" id="accountInfoForm">
                    <?php $this->renderView('/partials/modals/forms/__account') ; ?>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="accountInfoForm">Salvar</button>
            </div>
        </div>
    </div>
</div>