<div id="top-bar" class="container-fluid p-3 px-md-4 mb-3">
    <div class="row">
        <div class="col-6 text-left">
            <a href="/"><img src="/images/logo-horizontal.svg" alt="" height="34"></a>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-outline-dark btn-sm" href="/login">Entrar</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-10 col-md-8  col-lg-6 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Registre-se agora!</h5>
                    <h6 class="card-subtitle mb-2 text-center text-muted">PhoneBook será a sua nova agenda de
                        contatos</h6>
                    <div class="card-text">

                        <form class="form-signin" id="signupForm">
                            <div class="form-label-group">
                                <input type="text" name="name" id="inputNome" class="form-control" placeholder="Nome"
                                       required autofocus>
                                <label for="inputNome">Nome</label>
                            </div>

                            <div class="form-label-group">
                                <input type="email" name="email" id="inputEmail" class="form-control"
                                       placeholder="Email" required>
                                <label for="inputEmail">Email</label>
                            </div>

                            <div class="form-label-group">
                                <input type="text" name="phone" id="inputPhone" class="form-control"
                                       placeholder="Telefone" required>
                                <label for="inputPhone">Telefone</label>
                            </div>

                            <div class="form-label-group">
                                <input type="password" name="password" id="inputPassword" class="form-control"
                                       placeholder="Senha"
                                       required>
                                <label for="inputPassword">Senha</label>
                            </div>
                            <div class="form-label-group">
                                <input type="password" name="passwordConfirm" id="inputConfirmPassword"
                                       class="form-control"
                                       placeholder="Confirmar senha"
                                       required>
                                <label for="inputConfirmPassword">Confirmar senha</label>
                            </div>


                            <button class="btn btn-lg btn-dark btn-block" type="submit">Registrar</button>

                        </form>
                    </div>
                </div>
            </div>
            <p class="mt-5 mb-3 text-muted text-center">&copy; 2018</p>
        </div>
    </div>

</div>