<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="accountInputName">Nome</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><span
                                class="form-contact__field-icon oi oi-person"></span></span>
                    </div>
                    <input type="text" name="name" class="form-control" id="accountInputNameAcc" required>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="accountInputEmail">Email</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><span
                                class="form-contact__field-icon oi oi-envelope-closed"></span></span>
                    </div>
                    <input type="email" name="email" class="form-control" id="accountInputEmail" required>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="accountInputPhone">Telefone</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><span
                                class="form-contact__field-icon oi oi-phone"></span></span>
                    </div>
                    <input type="text" name="phone" class="form-control" id="accountInputPhone" required>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="accountInputPasswordPrevious">Senha antiga</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><span
                                class="form-contact__field-icon oi oi-key"></span></span>
                    </div>
                    <input type="password" name="passwordPrevious" class="form-control"
                           id="accountInputPasswordPrevious" required>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="accountInputPassword">Nova senha</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><span
                                class="form-contact__field-icon oi oi-key"></span></span>
                    </div>
                    <input type="password"  name="password" class="form-control" id="accountInputPassword" required>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="accountInputPasswordConfirm">Confirmação de senha</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><span
                                class="form-contact__field-icon oi oi-key"></span></span>
                    </div>
                    <input type="password"  name="passwordConfirm" class="form-control"
                           id="accountInputPasswordConfirm" required>
                </div>
            </div>
        </div>
    </div>
</div>