<div id="top-bar" class="container-fluid p-3 px-md-4 mb-3">
    <div class="row">
        <div class="col-6 text-left">
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-outline-dark btn-sm" href="/">Home</a>
        </div>
    </div>
</div>

<div class="container">
    <form class="form-signin" id="adminSigninForm" action="/admin-dashboard.php">
        <div class="text-center mb-4">
            <img class="mb-4" src="/images/logo.svg" alt="" width="150" height="150">
            <h4>PAINEL ADMINISTRATIVO</h4>
        </div>

        <div class="form-label-group">
            <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email" required
                   autofocus>
            <label for="inputEmail">Email</label>
        </div>

        <div class="form-label-group">
            <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Senha" required>
            <label for="inputPassword">Senha</label>
        </div>

        <button class="btn btn-lg btn-dark btn-block" type="submit">Entrar</button>
        <p class="mt-5 mb-3 text-muted text-center">&copy; 2018</p>
    </form>
</div>